'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Gm_Tool.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property button_quick_entrance_warrecord_02() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("button_quick_entrance_warrecord_02", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property button_quick_entrance_warrecord_03() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("button_quick_entrance_warrecord_03", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property button_select_big_left_titanium_type02_01() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("button_select_big_left_titanium_type02_01", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property common_button_titanium_infoview_big_01() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("common_button_titanium_infoview_big_01", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property common_button_titanium_lock_01() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("common_button_titanium_lock_01", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property common_button_titanium_lock_04() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("common_button_titanium_lock_04", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property common_mark_icon_unknown_middle() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("common_mark_icon_unknown_middle", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property common_mark_menu_chatting_whisper() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("common_mark_menu_chatting_whisper", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property common_mark_monster_type_use_15_devil() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("common_mark_monster_type_use_15_devil", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property common_mark_state_pk_normal() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("common_mark_state_pk_normal", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property common_mark_titanium_special() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("common_mark_titanium_special", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property game_button_main_menu_option_01() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("game_button_main_menu_option_01", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property game_button_main_menu_option_02() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("game_button_main_menu_option_02", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property game_button_tab_copper_inventory_all_01() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("game_button_tab_copper_inventory_all_01", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property game_button_tab_copper_inventory_all_03() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("game_button_tab_copper_inventory_all_03", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property game_button_tab_copper_inventory_book_01() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("game_button_tab_copper_inventory_book_01", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property game_button_tab_copper_inventory_book_03() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("game_button_tab_copper_inventory_book_03", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property game_button_tab_copper_inventory_consumption_01() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("game_button_tab_copper_inventory_consumption_01", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property game_button_tab_copper_inventory_consumption_03() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("game_button_tab_copper_inventory_consumption_03", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property game_button_tab_copper_inventory_creature_01() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("game_button_tab_copper_inventory_creature_01", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property game_button_tab_copper_inventory_creature_03() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("game_button_tab_copper_inventory_creature_03", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property game_button_tab_copper_inventory_enhance_01() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("game_button_tab_copper_inventory_enhance_01", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property game_button_tab_copper_inventory_enhance_03() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("game_button_tab_copper_inventory_enhance_03", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property game_button_tab_copper_inventory_equip_01() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("game_button_tab_copper_inventory_equip_01", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property game_button_tab_copper_inventory_equip_03() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("game_button_tab_copper_inventory_equip_03", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property game_button_tab_copper_inventory_etc_01() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("game_button_tab_copper_inventory_etc_01", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property game_button_tab_copper_inventory_etc_03() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("game_button_tab_copper_inventory_etc_03", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property game_button_tab_copper_inventory_khroo_01() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("game_button_tab_copper_inventory_khroo_01", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property game_button_tab_copper_inventory_khroo_03() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("game_button_tab_copper_inventory_khroo_03", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property game_button_tab_copper_inventory_quest_01() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("game_button_tab_copper_inventory_quest_01", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property game_button_tab_copper_inventory_quest_03() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("game_button_tab_copper_inventory_quest_03", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property game_button_tab_copper_inventory_skillcard_01() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("game_button_tab_copper_inventory_skillcard_01", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property game_button_tab_copper_inventory_skillcard_03() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("game_button_tab_copper_inventory_skillcard_03", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property game_button_titanium_inventory_bag_02() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("game_button_titanium_inventory_bag_02", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property game_button_titanium_inventory_repairlist_01() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("game_button_titanium_inventory_repairlist_01", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property game_button_titanium_player_character_01() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("game_button_titanium_player_character_01", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property game_button_titanium_player_character_04() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("game_button_titanium_player_character_04", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property game_button_titanium_player_skill_investment_01() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("game_button_titanium_player_skill_investment_01", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property game_button_titanium_player_skill_investment_02() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("game_button_titanium_player_skill_investment_02", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property game_button_titanium_player_trade_01() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("game_button_titanium_player_trade_01", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property paper_plane_30pxAd() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("paper_plane_30pxAd", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property paper_plane_30pxnote() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("paper_plane_30pxnote", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property treasure_map_30px() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("treasure_map_30px", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
